# Generated by Django 3.0.5 on 2020-04-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='tag',
            field=models.ManyToManyField(to='webapp.Tag'),
        ),
    ]
