# Generated by Django 3.0.5 on 2020-05-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_products_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(blank=True, choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='webapp.Tag'),
        ),
    ]
